MvcCoreNuevo/Controllers/CochesController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreNuevo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcCoreNuevo.Controllers
{
    public class CochesController : Controller
    {
        private List<Coche> GetCoches()
        {
            List<Coche> coches = new List<Coche>();
            Coche car = new Coche
            {
                IdCoche = 1,
                Marca = "Ford",
                Modelo = "Mustang",
                VelocidadMaxima = 320
            };
            coches.Add(car);
            car = new Coche
            {
                IdCoche = 2,
                Marca = "Seat",
                Modelo = "600",
                VelocidadMaxima = 95
            };
            coches.Add(car);
            car = new Coche
            {
                IdCoche = 3,
                Marca = "Fiat",
                Modelo = "Panda",
                VelocidadMaxima = 105
            };
            coches.Add(car);
            car = new Coche
            {
                IdCoche = 4,
                Marca = "Opel",
                Modelo = "Astra",
                VelocidadMaxima = 140
            };
            coches.Add(car);
            car = new Coche
            {
                IdCoche = 5,
                Marca = "Nissan",
                Modelo = "Kaskai",
                VelocidadMaxima = 200
            };
            coches.Add(car);
            return coches;
        }
        public IActionResult Index()
        {
            return View(this.GetCoches());
        }

        public IActionResult CochesAsincronos()
        {
            return View();
        }

        public IActionResult GetCochesPartial()
        {
            List<Coche> coches = this.GetCoches();
            //Busca en su carpeta de controller (Coches) o en Shared
            return PartialView("_CochesPartial", coches);
        }

        public IActionResult GetDetallesPartial(int id) //tiene que llamarse id por el
                                                        //mapa de rutas del startup
        {
            Coche car = this.GetCoches().SingleOrDefault(z => z.IdCoche == id);
            return PartialView("_DetallesCochePartial", car);
        }
    }
}

MvcCoreNuevo/Controllers/DepartamentosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreNuevo.Models;
using MvcCoreNuevo.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcCoreNuevo.Controllers
{
    public class DepartamentosController : Controller
    {
        private IRepositoryHospital repo;

        public DepartamentosController(IRepositoryHospital repo)
        {
            this.repo = repo;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int id)
        {
            return View(this.repo.BuscarDepartamento(id));
        }

        public IActionResult PaginarVistaDeptRegistro(int? posicion)
        {
            //SI NO EXISTE POSICION, MOSTRAMOS EL PRIMER REGISTRO
            if (posicion == null)
            {
                posicion = 1;
            }
            int ultimo = this.repo.GetNumeroRegistrosVistaDepartamento();
            int siguiente = posicion.Value + 1;
            //DEBEMOS COMPROBAR QUE NO NOS PASAMOS...
            if (siguiente > ultimo)
            {
                siguiente = ultimo;
            }
            int anterior = posicion.Value - 1;
            if (anterior < 1)
            {
                anterior = 1;
            }
            VistaDept dept = this.repo.GetRegistroDepartamento(posicion.Value);
            ViewData["ultimo"] = ultimo;
            ViewData["siguiente"] = siguiente;
            ViewData["anterior"] = anterior;
            ViewData["posicion"] = posicion.Value;
            return View(dept);
        }

        public IActionResult PaginarVistaDeptGrupo(int? posicion)
        {
            //COMPROBAMOS SI HEMOS RECIBIDO POSICION
            if (posicion == null)
            {
                posicion = 1;
            }
            //<a href=paginagrupo?posicion=1>Página 1</a>
            //<a href=paginagrupo?posicion=3>Página 2</a>
            //<a href=paginagrupo?posicion=5>Página 3</a>
            //int numeropagina = 1;
            //int numregistros = this.repo.GetNumeroRegistrosVistaDepartamento();
            //BUCLE QUE IRÁ DESDE LA POSICIÓN 1 HASTA NÚMERO
            //DE REGISTROS MOVIÉNDOSE EN LOS ELEMENTOS PAGINADOS (2)
            //String html = "<div>";
            //for (int i = 1; i <= numregistros; i += 2)
            //{
            //    html += "<a href='PaginarVistaDeptGrupo?posicion="
            //        + i + "'>Página " + numeropagina + "</a> | ";
            //    numeropagina++;
            //}
            //html += "</div>";
            //ViewData["paginas"] = html;
            ViewBag.numeropagina = 1;
            ViewBag.totalregistros = this.repo.GetNumeroRegistrosVistaDepartamento();
            List<VistaDept> departamentos = this.repo.GetGrupoDepartamentos(posicion.Value);
            return View(departamentos);
        }

        public IActionResult PaginarRegistroDepartamentoSQL(int? posicion)
        {
            if (posicion == null)
            {
                posicion = 1;
            }
            int ultimo = 0;
            Departamento departamento = this.repo.GetDepartamentoPosicion(posicion.Value, ref ultimo);
            int siguiente = posicion.Value + 1;
            //DEBEMOS COMPROBAR QUE NO NOS PASAMOS...
            if (siguiente > ultimo)
            {
                siguiente = ultimo;
            }
            int anterior = posicion.Value - 1;
            if (anterior < 1)
            {
                anterior = 1;
            }
            ViewData["ultimo"] = ultimo;
            ViewData["siguiente"] = siguiente;
            ViewData["anterior"] = anterior;
            ViewData["posicion"] = posicion.Value;
            return View(departamento);
        }

        public IActionResult PaginarGrupoDepartamentosSQl(int? posicion)
        {
            if (posicion == null)
            {
                posicion = 1;
            }
            //le damos un valor por defecto que luego
            //se cambiará de nuevo en el procedimiento
            int numregis = 0;
            List<Departamento> departamentos =
                this.repo.GetGrupoDepartamentosSQL(posicion.Value, ref numregis);
            ViewData["numregis"] = numregis;
            return View(departamentos);
        }
    }
}

MvcCoreNuevo/Controllers/TrabajadoresController.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreNuevo.Models;
using MvcCoreNuevo.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcCoreNuevo.Controllers
{
    public class TrabajadoresController : Controller
    {
        IRepositoryHospital repo;

        public TrabajadoresController(IRepositoryHospital repo)
        {
            this.repo = repo;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult PaginarGrupoTrabajadoresSQl(int? posicion, int? salario)
        {
            int numregis = 0;
            if (posicion == null)
            {
                posicion = 1;
            }
            List<Trabajador> trabajadores;
            if (salario == null)
            {
                trabajadores =
                    this.repo.GetGrupoTrabajadoresSQL(posicion.Value, ref numregis);
            }
            else
            {
                trabajadores =
                    this.repo.GetGrupoTrabajadoresSQL(posicion.Value, salario.Value, ref numregis);
                ViewData["salario"] = salario.Value;
            }
            ViewData["numregis"] = numregis;
            return View(trabajadores);
        }

        [HttpPost]
        public IActionResult PaginarGrupoTrabajadoresSQl(int salario)
        {
            int numregis = 0;
            int posicion = 1;
            List<Trabajador> trabajadores =
                this.repo.GetGrupoTrabajadoresSQL(posicion, salario, ref numregis);
            ViewData["numregis"] = numregis;
            ViewData["salario"] = salario;
            return View(trabajadores);
        }
    }
}

MvcCoreNuevo/ViewComponents/MenuDepartamentosViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MvcCoreNuevo.Models;
using MvcCoreNuevo.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcCoreNuevo.ViewComponents
{
    public class MenuDepartamentosViewComponent: ViewComponent
    {
        //PODEMOS TENER TODO LO QUE DESEEMOS, PERO TAMBIÉN
        //UN MÉTODO LLAMADO Task InvokeAsync()
        private IRepositoryHospital repo;

        public MenuDepartamentosViewComponent(IRepositoryHospital repo)
        {
            this.repo = repo;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Departamento> departamentos = this.repo.GetDepartamentos();
            return View(departamentos);
        }
    }
}

MvcCoreNuevo/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>@ViewData["Title"]</title>
    <!-- Bootstrap core CSS -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="~/css/jumbotron.css" rel="stylesheet" />
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <partial name="_PartialMenuUsuario" />
                @*<li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>*@
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Ejemplos</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item"
                           asp-controller="Coches"
                           asp-action="Index">Coches Ajax</a>
                        <a class="dropdown-item"
                           asp-controller="Departamentos"
                           asp-action="Index">Departamentos</a>
                        <a class="dropdown-item"
                           asp-controller="Trabajadores"
                           asp-action="Index">Trabajadores</a>
                    </div>
                </li>
                @await Component.InvokeAsync("MenuDepartamentos") 
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>

    <main role="main">

        <!-- Main jumbotron for a primary marketing message or call to action -->
        <div class="jumbotron">
            <div class="container">
                @RenderBody()
            </div>
        </div>

        <div class="container">
            
            <hr>

        </div> <!-- /container -->

    </main>

    <footer class="container">
        <p>&copy; Company 2021</p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="~/js/jquery-3.5.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>

MvcCoreNuevo/Views/Shared/_PartialMenuUsuario.cshtml
@{
    String usuario = Context.Session.GetString("username");
}

@if (usuario == null)
{
    <li class="nav-item active">
        <a class="nav-link text-primary"
           asp-action="LogIn"
           asp-controller="Home">
        Log In Usuario</a>
    </li>
}
else
{
    <li class="nav-item active">
        <a class="nav-link text-danger"
           asp-action="CloseSession"
           asp-controller="Home">
        Log Out @usuario</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">Perfil</a>
    </li>
    @*<li class="nav-item">
        <a class="nav-link" href="#">Pedidos</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">Comentarios</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="#">Modificar Datos</a>
    </li>*@
}